# Generated by Django 4.1.4 on 2023-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogImages',
            new_name='BlogImage',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=1, upload_to='uploads/blogimages'),
            preserve_default=False,
        ),
    ]
