# Generated by Django 4.1.4 on 2023-10-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_blogimages_blogimage_blog_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTags',
            new_name='BlogTag',
        ),
    ]
