# Generated by Django 4.1.4 on 2023-10-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_blogtags_blogtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
    ]
