# Generated by Django 4.1.4 on 2023-10-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_options_remove_blog_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(default='img alt', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogimage',
            name='img_alt',
            field=models.CharField(default='img_alt', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='img_alt',
            field=models.CharField(default='img alt', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='img_alt',
            field=models.CharField(default='img alt', max_length=40),
            preserve_default=False,
        ),
    ]
