# Generated by Django 4.1.4 on 2024-01-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_img_alt_blog_text_blogimage_img_alt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
