# Generated by Django 4.1.4 on 2024-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_testimonials_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('page', models.CharField(choices=[('home', 'Home'), ('gallery', 'Gallerie'), ('blog', 'Blog'), ('impressum', 'Impressum'), ('dataprotection', 'Datenschutzerklärung')], max_length=14)),
                ('text', models.TextField()),
                ('hero', models.ImageField(upload_to='uploads')),
                ('vert_position', models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom')], default='center', max_length=6)),
                ('hori_position', models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=6)),
            ],
        ),
    ]
