# Generated by Django 4.1.4 on 2024-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_alt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
